### ISSUE TITLE
Ruleset 7 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1018]
**DOT Hodler: The user held DOT every day from a specific date**

**Tasks**
- [ ] Create TEE unit test: Test Ruleset 7 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Test Ruleset 7 should fail successfully when no Substrate addresses are provided
- [ ] Create TEE unit test: Test Ruleset 7 should fail successfully when The Graph doesn’t return a HTTP 200 status code
- [ ] Create TEE unit test: Test Ruleset 7 should fail successfully when The Graph returns FALSE boolean values for all of the Substrate addresses provided

**Unit Test 1: Ruleset 7 succeeds** and generates a VC successfully

- **Generate VC** extrinsic within the TEE Enclave should be called
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param`: One or more Substrate addresses should be allowed to be defined within the payload of this param
- The extrinsic should then carry out a HTTPS request to **The Graph** provided by the TDF team. It would check to ensure the URL returns a 200 HTTP status code and check a boolean value is return for each of the addresses provide to **The Graph** in the request.

**Unit Test 2: Ruleset 7 should fail** successfully **when no Substrate addresses are provided**

- **Generate VC** extrinsic within the TEE Enclave should be called
    - `ruleset-id` param relating to the set of rules we need to test against
    - idhub-address param relating to the unique Litentry/IDHub address
    - `param`: One or more Substrate addresses should be allowed to be defined within the payload of this param
- If no Substrate addresses have been provide in the param payload then the extrinsic should **not** attempt to call any 3rd party services and should fail to generate a VC.

**Unit Test 3: Ruleset 7** should **fail** successfully **when The Graph doesn’t return a HTTP 200 status code**

- **Generate VC** extrinsic within the TEE Enclave should be called
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param`: One or more Substrate addresses should be allowed to be defined within the payload of this param
- The extrinsic should find that at least one Substrate address has been provided
- However, the test should fail successfully if The Graph endpoint does not return an HTTP 200 status code

**Unit Test 4: Ruleset 7** should **fail** successfully **when The Graph returns FALSE boolean values for all of the Substrate addresses provided**

- **Generate VC** extrinsic within the TEE Enclave should be called
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param`: One or more Substrate addresses should be allowed to be defined within the payload of this param
- The extrinsic should find that at least one Substrate address has been provided
- The Graph endpoint should return an HTTP 200 status code
- However, the test should fail successfully if none of the Substate addresses provided have held DOT every day from a specific date.
