### ISSUE TITLE
Ruleset 6 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1031]
**Tasks**
- [ ] Create TEE unit test: Check Ruleset 6 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Check Ruleset 6 should fail successfully when no Twitter account is provided
- [ ] Create TEE unit test: Check Ruleset 6 should fail successfully when no Twitter is linked
- [ ] Create TEE unit test: Check Ruleset 6 should fail successfully when none of the Twitter accounts provided qualify for any of the follower ranges

**Details**

**Unit Test 1:** Ruleset 6 succeeds and generates a VC successfully 
(Ref: User has at least x amount of followers)
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` one or more Twitter accounts specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the Twitter defined in the `param` payload and check to see if the accounts provided have been both linked and verified against the `idhub-address`
- The extrinsic should then perform an HTTPS request to establish how many followers the Twitter account(s) have
- The amount of followers needs to be checked against Ruleset 8. If the user has qualified for one or more of these ranges (> 1 follower, >100 followers, >1K followers, >10K followers, 100K followers ) then a VC should be generated
- The unit test should be marked as passed if the VC generates and Parachain extrinsic is successfully called

**Unit Test 2:** Check Ruleset 6 should fail successfully when no Twitter account is provided

**Unit Test 3:** Create Ruleset 6 should fail successfully when no Twitter is linked

**Unit Test 4:** Check Ruleset 6 should fail successfully when none of the Twitter accounts provided qualify for any of the follower ranges
