### ISSUE TITLE
Ruleset 5 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1032]
**Tasks**
- [ ] Create TEE unit test: Check Ruleset 5 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Check Ruleset 5 should fail successfully when the tweet URL is not provided
- [ ] Create TEE unit test: Check Ruleset 5 should fail successfully when the tweet URL does not return a HTTP 200 status code
- [ ] Create TEE unit test: Check Ruleset 5 should fail successfully when the tweet returned on the URL request finds that the tweet doesn’t contain the correct content

**Details**

**Unit Test 1:** Ruleset 5 succeeds and generates a VC successfully 
(Ref: User follows on Twitter and has retweeted a tweet)
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a specific tweet URL (public) should be provided by the controller (user) on the F/E. This tweet URL would be then defined within the payload of this param
- The extrinsic should then carry out a HTTPS request to tweet URL. It would check to ensure the URL returns a 200 HTTP status code and that the content of the tweet is correct
- A check should be performed to look-up and check the Twitter account which posted the tweet is both linked and verified against the `idhub-address`

**Unit Test 2:** Ruleset 5 should fail successfully when the tweet URL is not provided
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a specific tweet URL (public) should be provided by the controller (user) on the F/E. This tweet URL would be then defined within the payload of this param
- If the F/E has not passed a tweet URL into the `param` payload then the extrinsic should fail to generate a VC

**Unit Test 3:** Ruleset 5 should fail successfully when the tweet URL does not return a HTTP 200 status code
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a specific tweet URL (public) should be provided by the controller (user) on the F/E. This tweet URL would be then defined within the payload of this param
- The extrinsic should find that the tweet URL has been provide
- However, the test should fail successfully if the tweet URL does not return a HTTP 200 status code

**Unit Test 4:** Ruleset 5 should fail successfully when the tweet returned on the URL request finds that the tweet doesn’t contain the correct content**
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a specific tweet URL (public) should be provided by the controller (user) on the F/E. This tweet URL would be then defined within the payload of this param
- The extrinsic should find that the tweet URL has been provide
- The tweet URL should return a HTTP 200 status code
- However, the test should fail successfully if the tweet URL does not return the correct content within the tweet
