### ISSUE TITLE
Ruleset 4 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1033]
**Tasks**
- [ ] Create TEE unit test: Check Ruleset 4 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Check Ruleset 4 should fail successfully when no address is provided
- [ ] Create TEE unit test: Check Ruleset 4 should fail successfully when no address is linked
- [ ] Create TEE unit test: Check Ruleset 4 should fail successfully when the address doesn’t hold any LIT token

**Details**

 **Unit Test 1: Ruleset 4 succeeds** and generates a VC successfully 
(Ref: LIT Holder)
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a Discord account specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the address defined in the `param` payload and check to see if that address has been both linked and verified against the `idhub-address`
- The test should then check to see that the address holds 1+ LIT token(s)
- The unit test should be marked as passed if the VC generates and Parachain extrinsic is successfully called

**Unit Test 2: Ruleset 4** should **fail** successfully **when no address is provided**
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` an address specified by the controller (user) on the F/E pass this address within the payload of this param
- If the F/E has not passed an address in the `param` payload then the extrinsic should fail to generate a VC

 **Unit Test 3: Ruleset 4** should **fail** successfully **when no address is linked**
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` an address specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the address defined in the `param` payload and check to see if that address has been both linked and verified agains the `idhub-address`
- It should fail successfully if the F/E has passed in a address which is not linked and verified against the `idhub-address`

**Unit Test 4: Ruleset 4** should **fail** successfully **when the address doesn’t hold any LIT token**
- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` an address specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the address defined in the `param` payload and check to see if that address has been both linked and verified agains the `idhub-address`
- The test should successfully find the address is linked and verified against the `idhub-address`
- However, the test should fail successfully when it finds that address does **not** hold any LIT token
