### ISSUE TITLE
Ruleset 2 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1035]
**Tasks**
- [ ] Create TEE unit test: Check Ruleset 2 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Check Ruleset 2 should fail successfully when no Discord account is provided
- [ ] Create TEE unit test: Check Ruleset 2 should fail successfully when no Discord account is linked
- [ ] Create TEE unit test: Check Ruleset 2 should fail successfully when the Discord account doesn’t have the role “ID-Hubber”

**Details**

**Unit Test 1: Check Ruleset 2 succeeds** and generates a VC successfully 
(Ref: Becoming an “ID-Hubber”)

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a Discord account specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the `ruleset-id` param and run the associated  functionality which should validate the following are true:
  - The `idhub-address` should check the Discord account specified in the `param` payload is both linked and verified
  - If this passes the TEE needs to check that the Discord account has the role “ID-Hubber”
  - If both conditions are **true** the TEE should create a VC in the format of a credential schema (JSON) Ref: [https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-credential](https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-credential)
  - The TEE should then callback the a Parachain extrinsic (e.g. **VCGenerated**) and pass the VC to it
  - The unit test should be marked as passed if the VC generates and Parachain extrinsic is successfully called

**Unit Test 2: Check Ruleset 2** should **fail** successfully **when no Discord account is provided**

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a Discord account specified by the controller (user) on the F/E should be defined within the payload of this param
- If the F/E has not passed a Discord account in the `param` payload then the extrinsic should fail to generate a VC

**Unit Test 3: Ruleset 2** should **fail** successfully **when no Discord account is linked**

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a Discord account specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the Discord account defined in the `param` payload and check to see if that Discord account has been both linked and verified agains the `idhub-address`
- It should fail successfully if the F/E has passed in a Discord account which is not linked and verified against the `idhub-address`

**Unit Test 4: Ruleset 2** should **fail** successfully **when the Discord account doesn’t have the role “ID-Hubber”**

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param ****relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
    - `param` a Discord account specified by the controller (user) on the F/E should be defined within the payload of this param
- The extrinsic should then look-up the Discord account defined in the `param` payload and check to see if that Discord account has been both linked and verified agains the `idhub-address`
- The test should successfully find the Discord is linked and verified against the `idhub-address`
- However, the test should fail successfully when it finds that Discord account has **not** been assigned the role of “ID-Hubber”
