### ISSUE TITLE
Follow-up of DI: ts-tests of direct invocation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1682]
### Context

We should be able to start adding ts-tests for the direct invocation based on the demo code in https://github.com/litentry/litentry-parachain/pull/1676

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang @Verin1005 in a nutshell, these should be more or less a copy of the tests in `tee-worker/ts-tests/identity.test.ts` and `tee-worker/ts-tests/vc.test.ts`, correct?

**Comment by Kailai-Wang** [comment]
Yes - it would be great if we can reuse some code.

Additionally it should cover `UnauthorisedSigner` error case (means e.g. user A can't create an identity for user B)

**Comment by Kailai-Wang** [comment]
Something to add:
we should test the trusted getter too => I have some demo code in https://github.com/litentry/litentry-parachain/pull/1732, but it only covers user shielding key query (I think it's sufficient for demo purpose)

For II we verify the sidechain storage by querying the raw storage to tell e.g. if the shielding key is really set in sidechain.
For DI we now have dedicated getters

**Comment by arieljbirnbaum** [comment]
To track this better, I'm listing the existing test suites here.
For each one that needs to be reimplemented in DI, I'll open a separate issue.
I don't know yet if all of these are supported under DI though; that needs to be checked.

- [x] `identity.test` (in progress; see #1889)
- [x] `vc.test`
- [ ] `batch.test`
- [x] `bulk_identity.test`
- [x] `bulk_vc.test`
- ~`resuming_worker.test`~ There are no extrinsic invocations here so DI is not relevant

**Comment by Kailai-Wang** [comment]
@Verin1005 @grumpygreenguy Could you please update the status of this ticket? I assume most of the tasks have been done

**Comment by 0xverin** [comment]
>To track this better, I'm listing the existing test suites here.
For each one that needs to be reimplemented in DI, I'll open a separate issue.
I don't know yet if all of these are supported under DI though; that needs to be checked.

Updates:
- [x] `di_substrate_identity.test` (done; see #1889)
- [x] `di_evm_identity.test` (done; see #1956)
- [x] `di_vc.test `(done; see #2035)
- [x] `bulk_identity.test && bulk_vc.test`(done; see #2054)

**Comment by 0xverin** [comment]
I think this issue can be closed now, as the testing for DI is essentially completed
