### ISSUE TITLE
ts-tests: pin node and yarn versions

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1885]
### Context

@kziemianek [reported](https://litentry.slack.com/archives/C05328L0GAF/p1689240026309089) issues running the parachain-api build script on a clean repo; the issue boiled down to an incompatible node.js version --- the build runs cleanly on v16, but fails on v20.

We should ensure that the scripts are run under the expected version of node; the de-facto standard way to do that is with [nvm](https://github.com/nvm-sh/nvm)

NB: we should _also_ make our scripts compatible with the latest node before [v16 goes end-of-life in September](https://github.com/nodejs/release#release-schedule); that will be tracked by #1886 

We also have issues with pinning the Yarn version; the current method (`yarn set version stable`) adds changes to the `.yarnrc.yml` file which would break if we don't commit the `.yarn/releases` folder (which we definitely _don't_ want); the fix for that is to run Yarn via [corepack](https://nodejs.org/docs/latest-v16.x/api/corepack.html) instead so it takes the `packageManager` version from `package.json`

### Task

- [ ] Add an .nvmrc file to `tee-worker/ts-tests` to pin down the node version
- [ ] Update the docker files to use `nvm` to install and use the specified node version
- [ ] Update the yarn scripts to use `corepack yarn` instead (or introduce an alias to override the global installation?)
- [ ] Update developer documentation (i.e. the relevant page under the [Onboarding](https://www.notion.so/web3builders/Onboarding-18974d4564504bf78f904cd12a1a8b5d?pvs=4) document) with links and examples on nvm and corepack usage

(@Kailai-Wang @Verin1005 please weigh in regarding priority)

**Comment by 0xverin** [comment]
I consider this to be of medium priority, at least after our DI test phase.

**Comment by Kailai-Wang** [comment]
It's not blocking any dev progress but if it can be done within 1-2 days, I'll rate it as `high` priority as it's the fundamental tool setting that can affect all devs
