### ISSUE TITLE
ts-tests: make compatible with Node 20

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1886]
### Context

As tested by @kziemianek, the `typegen` scripts throw the dreaded `Unknown file extension ".ts"` message under Node 20 (the script returns "successfully", but the build breaks later on :roll_eyes:).

It currently works OK with Node 16 (and we can [ensure](https://github.com/litentry/litentry-parachain/issues/1885) that the scripts run with it), but this version is [reaching end-of-life in September](https://github.com/nodejs/release#release-schedule), so we need to make sure to switch before that. Version 20 will enter LTS in October this year, so we should target that version already (rather than 18).

### Task

- [x] Make sure the build and test scripts run cleanly under Node 20
- [x] Update the nvmrc (assuming #1885 is done)
- [x] Update the docker files accordingly

**Comment by kziemianek** [comment]
Node version was bumped in #2435 , can this be closed @Traf333 @grumpygreenguy ?

**Comment by Traf333** [comment]
Good catch, yes every point was resolved within https://github.com/litentry/litentry-parachain/pull/2435,
the evidence: https://github.com/litentry/litentry-parachain/actions/runs/7697026419
