### ISSUE TITLE
DI tests: identity

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1889]
## Context

See #1682 

## Task

Implement each of the following test steps using the DI interface.
Refactor and extract common functionality as needed, and establish a pattern for the remaining test suites.
If needed, merge to dev in smaller batches to mitigate conflicts with other developments.

Along the way, consider better options for reducing the combinational explosion :P

### Steps

- [x] `check user sidechain storage before create`
- [x] `Invalid user shielding key`
- [x] `set user shielding key`
- [x] `check user shielding key from sidechain storage after setUserShieldingKey`
- [x] `check idgraph from sidechain storage before linking`
- [x] `link identities`
- [x] `check IDGraph after LinkIdentity`
- [x] `link invalid identities`
- [x] `link identities with wrong signature`
- [x] `deactivate identities`
- [x] `check IDGraph after deactivate identity`
- [x] `deactivate prime identity is disallowed`
- [x] `activate identity`
- [x] `check IDGraph after activate identity`
- [ ] `set error user shielding key`
- [ ] `exceeding IDGraph limit not allowed`

## Due Diligence

- [ ] Create issues for missing test cases from the original II test suite (marked with `TODO` comments in the code)

**Comment by 0xverin** [comment]
I believe it would be better for me to handle these tasks because I might be more familiar with the process. Additionally, it's suitable to test them in a single file, which is suitable for solo work. I am willing to fully dedicate myself to completing these todo lists this week. What do you think? @grumpygreenguy

**Comment by arieljbirnbaum** [comment]
Per @Verin1005. some error cases are not covered in the current suite; let's either add them here or document the debt in a followup issue

**Comment by 0xverin** [comment]
Due to changes in the dev branch, I have modified the step list.

**Comment by 0xverin** [comment]
Follow up test steps:
- [x] `evm-signer set shielding key`
- [x] `check sidechain storage after set`
- [x] `evm-signer link identity`
- [x] `check sidechain storage after link`
- [x] `evm-signer deactive identity`
- [x] `check sidechain storage after deactive`
- [x] `evm-signer activate identity`
- [x] `check sidechain storage after activate`

**Comment by 0xverin** [comment]
follow up:
- [x] `set_identity_networks`
- [x] `set_identity_networks`
