### ISSUE TITLE
small left over tasks from update upstream

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#2000]
### Context
As title, left over from [PR](https://github.com/litentry/litentry-parachain/pull/1969)

### Task
- [ ] changes about rm used docker images 
- [ ] Path of GLOBAL_SCHEDULED_ENCLAVE
- [ ] `light_client_db.bin` should be `light_client_db`. It’s a folder now. Mistake during update.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Done by https://github.com/litentry/litentry-parachain/pull/2258
