### ISSUE TITLE
token bridge backend test using Rinkeby

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#363]
### Context
Before the Ethereum Mainnet, all contracts and relayers be verified in Ethereum Testnet

### Task
- [x] Deploy the bridge contracts in the Rinkeby test network
- [x] Deploy the relayers
- [x]  Enable and Deploy bridge pallets in staging
- [x]  Test the basic function token from Rinkeby to staging network

### Acceptance criteria
- [x] Token successfully minted in staging network

**Comment by suinuj** [comment]
1 Deploy the bridge contracts in the Ropsten test network
2 Deploy the relayers 
3 Enable and Deploy bridge pallets in staging 
4 test the token from Ropsten to staging

**Comment by wangminqi** [comment]
Rinkeby testnet is ready.
For contract address
https://www.notion.so/litentry/Parachain-Token-Bridge-1a219bb4e1e849abbaad4c7a2e08185d

**Comment by suinuj** [comment]
the token transfer from Rinkeby to litmus is successful.
