### ISSUE TITLE
UI integration test with staging environment

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#364]
### Context
Test UI for token bridge function

### Task
- [x] Deploy UI with staging network
- [x] Test token transfer triggered from UI

### Acceptance criteria
- [x] UI can send the correct transaction to contract and token minted in staging network

**Comment by suinuj** [comment]
1 Deploy the UI in staging with support of call bridge contract
2 Test the token flow with UI

**Comment by h4n0** [comment]
Token bridge related information: https://www.notion.so/litentry/Parachain-Token-Bridge-1a219bb4e1e849abbaad4c7a2e08185d

**Comment by h4n0** [comment]
Blocked by https://github.com/litentry/project-gmbh-all-hands-board/issues/83

**Comment by StamfordDigital** [comment]
@suinuj Please update this ticket with the result and close when complete. Thank you.

**Comment by suinuj** [comment]
test was passed in staging environment with web app UI.
