### ISSUE TITLE
list exceptional test case

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#365]
### Context
After the basic function is verified, list the exceptional test cases and run them

### Task
- [x] List exceptional test cases for token bridge 
- [x] Run test cases and check the robustness of bridge solution

### Acceptance criteria
- [x] bridge can handle some exceptional cases

**Comment by suinuj** [comment]
1 list some exceptional test cases for token bridge
2 execute the test and solution to fix it

**Comment by wangminqi** [comment]
how to restart everything and clean/deal with unfinished cross-chain orders:
Case 1: Majority of relay go offline
Case 2: If token bridge runs out of gas (ethereum/substrate)
Case 3: Pressure test
Case 4: If transaction missed in the middle, the standard procedure to deal with

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Parachain-Token-Bridge-Test-Process-51bb642ca13c428eae6ec5179b5f56ec
Test related procedure and tool reference here.

**Comment by h4n0** [comment]
All listed test cases have been tested and passed. close.

**Comment by h4n0** [comment]
All listed test cases have been tested and passed. close.
