### ISSUE TITLE
documentation for bridge usage for Litmus

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#366]
### Context
write the documentation for token bridge step by step

### Task
- [x] Documentation, doc review and publish
- [x] Invite non technical people follow the doc and complete token transfer

### Acceptance criteria
- [x] Non technical people can complete token transfer by referring the doc

**Comment by suinuj** [comment]
write documentation for users to import LIT to Litmus step by step

**Comment by StamfordDigital** [comment]
Documentation is now on Gitbook.
