### ISSUE TITLE
deploy contracts in Ethereum

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#367]
### Context
Before the token bridge onboard, contracts deployed in Ethereum Mainnet

### Task
- [ ] Deploy the contracts and verify ABI
- [ ] Keep the private key safe and private key keeper knows how to handle the emergence

### Acceptance criteria
- [ ] Successfully deployed contracts and key management

**Comment by suinuj** [comment]
Before token bridge onboard, deploy bridge contracts in Ethereum

**Comment by h4n0** [comment]
Completed.
