### ISSUE TITLE
Update dependencies to `polkadot-v0.9.17`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#375]
### Context

`polkadot-v0.9.17` is released: https://github.com/paritytech/polkadot/releases
Allegedly it fixes the slow block production on kusama.

### Task
- [x] update the code to it
- [x] client update for Litmus
- [x] (optional) on-chain runtime upgrade on Litmus

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
