### ISSUE TITLE
PNS support & sync for onboarding preparation

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#380]
### Context
Support the PNS pallet onboarding

### Task
- [ ] Sync with PNS colleagues
- [ ] Code review
- [ ] Test review & adaptation to our parachain CI

### Acceptance criteria
- [ ] PNS PR is ready to merge

**Comment by h4n0** [comment]
duplicated
