### ISSUE TITLE
Use multisig for contract admin key 

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#386]
### Context
We need to decide how to make contract admin key safe.
1. multiple signer
2. single account

### Task
- [x] discuss which solution is better 
- [x] determine M/N parameter and account owner for solution 1. prepare script and teach owner how to use it.

### Acceptance criteria
- [ ] solution determined and rehearsal in staging environment

**Comment by wangminqi** [comment]
#414 to follow
