### ISSUE TITLE
Distribute crowdloan rewards on Litmus

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#397]
### Context
Litmus crowdloan rewards distribution.

### Task
- [x] Set sufficient balance for a crowdloan reward distribution account and lock same amount on ethereum simutalneously. 
- [x] Generate encoded call hex of reward distribution batch
- [x] Use sudo to sign and send encoded calls 
- [x] Verify if the distribution takes effect
- [ ] Write a documentation page about how users can claim for their vested rewards

### Acceptance criteria
Rewards has been successfully and correctly distributed to each contributor.

**Comment by h4n0** [comment]
Crowdloan distribution has been completed. Documentation needs to be done after the f/e UI is ready. A separate story has been created litentry/research-force#121
