### ISSUE TITLE
Reduce the number of hosts in parachain staging

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#401]
### Context

prerequisite for #346 
We are launching a rococo parachain soon, which is presumably more widely used for testing (than staging). Therefore we could reduce the resource consumption of staging env:
instead of 3 relayer + 2 parachain-collators, we are going to use 2 relayer + 1 parachain-collator

### Task
- [x] adjust the staging chain spec
- [x] adjust the deployment script for staging
- [x] adjust AWS settings for staging

### Acceptance criteria
The adjustment is done and the staging env can be operated as before

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
