### ISSUE TITLE
Update dependencies to `polkadot-v0.9.18`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#417]
### Context
`v0.9.18` was released: https://github.com/paritytech/polkadot/releases/tag/v0.9.18

### Task
- [x] Update upstream dependencies to this version and resolve the compilation errors.
- [ ] Release a new version
- [ ] Upgrade Litmus: both client + wasm

### Acceptance criteria
- version updated
- tests passed
- benchmarks updated
- TODOs in codes resolved (if any)
- Litmus upgraded

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
