### ISSUE TITLE
Generate and manage token bridge relayer accounts 

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#431]
### Context
Relayer accounts are needed to be generated and registered into Litmus

### Task
- [x] Generate 3 relayer accounts
- [x] Send balances to these accounts (sudo)
- [x] Register these 3 accounts into token bridge pallet (sudo)
- [x] Runtime upgrade (sudo)

### Acceptance criteria
Relayers work properly.

**Comment by suinuj** [comment]
https://www.notion.so/litentry/Token-bridge-deploy-in-Litmus-af7285f3587f42f5b8fcdea40e34d5f1

**Comment by suinuj** [comment]
Litmus upgrade is done.
