### ISSUE TITLE
Test token migration in rococo network via UI

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#464]
### Context
Test token migration in rococo network via UI

### Task
- [x] Upgrade runtime in rococo
- [x] Set up Relayer
- [x] Set up contract
- [x] Configure the bridge pallet 
- [x] Configure UI
- [x] Test token migration via UI

### Acceptance criteria
token transferred successfully in rococo network.

**Comment by h4n0** [comment]
Test on rococo parachain with UI passed. closed
