### ISSUE TITLE
Revisit devops setups for parachain nodes

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#567]
### Context
We are approaching launching the litentry parachain. We can take this opportunity to revisit our parachain node settings.

### Task
- [x] #548 
- [x] maybe increase `--ws-max-connections`
- [x] double-check the necessity of having a domain name for collators - do we really need it? (as it exposes the ws access to public if someone knows the domain name)
- [x] https://github.com/litentry/litentry-parachain/issues/598
  see https://docs.substrate.io/v3/runtime/custom-rpcs
  - We are forwarding all traffic to 80/443 to 9944, which is the ws socket. Is this OK? (we do not have `rpc-methods=Unsafe` or `--*-external`, so all requests will go through)
  - We are not exposing http-rpc port in any way, I guess that's fine
- [x] ~~consider launching the collators of litentry-parachain from EU~~

### Acceptance criteria
All tasks are completed.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
`ws-max-connections` was increated to 3000

**Comment by Kailai-Wang** [comment]
Keep all instances in SG for now. Reasons:
- collators in SG have been working well for Litmus
- we will have more collators once we allow third-party collators, which will help in even geographic distribution

**Comment by Kailai-Wang** [comment]
The domain names:
it's not necessary for the collators (although they should always be visible in network discovery), I removed the nginx <> SSL cert connection and deleted the route53 entries.

**Comment by Kailai-Wang** [comment]
All tasks resolved.
