### ISSUE TITLE
Create a multisig account for Litmus sudo

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#585]
### Context
We'd like to transit to a multisig account for Litmus sudo for better safety.

### Task
Create a multisig account after successful testing

### Acceptance criteria
- testing with multisig account on staging passed
- multisig account on Litmus created
- sudo account transferred and tested on Litmus

1 - 2 story points.
Will open another issue for Litentry transition after it goes online.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
multisig successfully tested on staging.

TODO:
- [x] create and test multisig account on Rococo
- [x] create and test multisig account on Litmus
- [x] transfer root to multisig account on Litmus

**Comment by Kailai-Wang** [comment]
It seems we ran into a deadlock on rococo:
we transferred `sudo` to multisig account without adjusting `baseCallFilter`. That means all operations using multisig account will be denied/filtered out even though multisig account is `sudo`, since extrinsic calls to `pallet-multisig` will be rejected.

With that being said, I see no way to work around this but resetting the rococo-parachain, unfortunately.
We should take this as a lesson and make sure the filter is correctly set before doing root transfer on Litmus

**Comment by Kailai-Wang** [comment]
Successfully restored state on rococo => we are now reverted to the state before multisig account was created.

A new chain spec (from block number #1700000) will be added.

see also https://github.com/paritytech/subport/issues/337

**Comment by Kailai-Wang** [comment]
root transfer done, will close this issue as soon as the pending extrinsic is finished.

**Comment by Kailai-Wang** [comment]
Done, rococo sudo back to the single account as well.
