### ISSUE TITLE
Litentry pre-launch checklist

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#591]
Onboarding date: **June 04**

For reference: [Litmus pre-launch checklist](https://github.com/litentry/research-force/issues/110)

### Runtime
- [ ] ~~double-check `baseCallFilter` to make sure we don't expose unwanted calls upon launching~~
- [ ] ~~double-check the runtime parameters and binding~~
- [ ] ~~recalculate the benchmarking~~

### Devops
- [x] launch instances (3 collators + 2rpc-nodes)
- [x] adjust deployment script: rundeck/ansible
- [x] make sure polkadot DB is synced
- [x] network setup: load balancer, p2p keys, collator keys
- [x] #567 

### Testing
- [x] testing of block production with the submitted genesis wasm
- [x] testing of runtime upgrade with the submitted genesis wasm => **important**

### Misc
- [x] double-check the submitted polkadot-js/apps config is up-to-date
- [x] #595

**Comment by Kailai-Wang** [comment]
Current status:
- testing of block production with genesis wasm OK
- testing of runtime upgrade from genesis wasm OK
- instances launched
- network settings applied
- polkadot-js/apps config updated

Polkadot DB is still in sync, will take a few days.

The tasks in the "Runtime" section will be done after the launch other than now. I'll include them in the post-launch checklist.

**Comment by wangminqi** [comment]
Shall we close this? I just close the roll-out plan. #595

**Comment by Kailai-Wang** [comment]
Sure, thanks
