### ISSUE TITLE
Move staging env out of AWS

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#596]
### Context
We'd like to migrate the non-production network out of AWS for better control. One example is the parachain staging network which has 3 servers and it's not performance-critical anyway.

### Task
migrate the parachain staging env from AWS to hetzner

### Acceptance criteria
- [x] new instances on Hetzner are launched
- [x] servers on AWS are shut down
- [x] script/network mapping is adjusted so that the auto-deployment script is not broken.

Not super urgent but would be good if we can do this in the near future.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by chenzongxiong** [comment]
@Kailai-Wang please close it if everything is ok

**Comment by Kailai-Wang** [comment]
Looks good, thanks @chenzongxiong
