### ISSUE TITLE
Litentry post-launch checklist

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#608]
This is a follow-up to #591 
Please note this list only includes the tasks that need to be done shortly after launching, it `doesn't` include all the planned features which will be onboarded later.

### First runtime upgrade
- [x] double-check the pallets that are integrated
- [x] double-check `baseCallFilter` to make sure we don't expose unwanted calls
- [x] double-check the runtime parameters and binding
- [x] recalculate the benchmarking

### Devops and Automation
- [x] #371 
- [x] #625
- [x] extra public host-service?
- [x] [parachain DB backup](https://github.com/litentry/litentry-parachain/issues/737)
- [x] Basic monitor and alerting system

### Documentation
- [x] update the Litentry part in gitbook doc

### Crowdloan distribution
- [x] #537 
- [x] #538 
- [x] #539 
- [x] #599 
- [x] #415 => this needs to be done for Litmus too

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Still relevant, a few tasks are not yet finished.
Let's not forget it

**Comment by Kailai-Wang** [comment]
All points addressed, closing it.
