### ISSUE TITLE
Better synchronization setup for TEE development

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#617]
### Context
Currenlty we are always using default branch (`dev`) of litentry-parachain in TEE dependencies, it's not so intuitive to sync to the desired commit and we are not free to check-in commits to `dev` branch for TEE-specific features. It also brings extra chaos when we upgrading dependencies across multiple repos.

### Task
My thought on this:
- have a dedicated branch for TEE development, e.g. `tee-dev`
- docker image that is used in TEE development (`litentry/litentry-parachain:tee`) can be auto. built upon commits.
- The TEE workers will always be built against this branch, including all the runtime dependencies
- This branch can fall behind `dev`, we merge the changes on `dev` to it only on demand.
- We can use tags on this branch if there're breaking changes

The overhead would be to maintain an extra branch, but as the codebase is basically synced with `dev` (we can backport the changes in this branch to `dev` too), so it should be too much of a problem.

The tasks should be:
- [x] set up the branch
- [x] adjust GHA to trigger a docker build upon push
- [x] adjust TOML files in TEE to refer to this branch
- [x] adjust build and integration test script to refer to this branch (if needed)

### Acceptance criteria
Extra branch is set up, worker's build flow is adjusted. 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
All completed, this issue can be closed.
