### ISSUE TITLE
Clean up the branching and commits of litentry/worker

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#626]
### Context
The current branching and commit history in litenry/worker is a bit chaotic:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/7630809/172386508-75377860-9a8c-4509-97da-f56b7a7b2328.png">

### Task
- [x] squash the commits so that we are only 1 commit ahead (which is our specific change)
- [x] use `dev` as default branch to be consistent with parachain repo
- [x] force to use "squash merge" on PR
- [x] create a new repo `tee-worker` as standalone repo
- [x] write a script to generate the patch to reflect the upstream changes
- [x] do the upstream upgrade once

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
My original question in the channel:

> In case anyone knows, is there a best practice to manage the forked branch and squash commit PR?
>Problem:
>- we have a [forked branch](https://github.com/litentry/worker)
>- we enable branch protection for the default branch
>- We use squash merge setting for PRs towards the default branch
> However, the commit history of the default branch still shows "x commits behind" the upstream branch, even though it's resolved in the [feature branch](https://github.com/litentry/worker/tree/upstream-sync-3e16b83), as the squash commit is seen as a totally different commit by github  which is not logged on the upstream branch history.
We could have used "Allow merge commits" setting, then we would have a linear history on the default branch (= no "x commits behind"), but our commit history in the feature branch would be retained in the default branch too.
In short, we want to use "squash merging" to a forked branch while keeping the history clean.
A workaround that I can think of is using two level feature branches, but that's too inconvenient.
> Has someone got better ideas?

It doesn't look like we have got a perfect solution here.

I'm thinking of using a plain repo instead of a forked repo, but keeping track of the upstream commit (like a `UPSTREAM_COMMIT.txt`) and we merge the upstream diffs regularly to stay synced => similar to the relationship between cumulus-parachain-node and litentry-parachain.

**Rationale:**
the only reason we want the "forked" repo is that we can see the diff intuitively (x commits behind, x commits ahead), but the commit diff is a mess anyway with squash merge. Please note we don't want to switch off squash merge as it would otherwise bloat the commit history easily.

We can even wrap up the worker as a subfolder in the parachain repo as we use our parachain as the parent chain now => we'll need to adjust CI though if we want to do that.

What do you reckon? @h4n0 @StamfordDigital @BillyWooo @wangminqi

**Comment by Kailai-Wang** [comment]
Conclusion after discussions with @BillyWooo
- we will create a standalone repo (non-forked) for tee-workers
- we will have a file to keep track of the aligned upstream commit
- whenever we want to update the upstream parts, we generate a patch that contains the diff between the stored upstream commit (where we are currently at) and the latest upstream HEAD commit, and apply this patch to our codebase. If there're conflicts, resolve them manually.

**Comment by Kailai-Wang** [comment]
It's done now

tee-worker repo is up and running and we have successfully done a codebase update.
