### ISSUE TITLE
Onboard governance v1.0 for Litmus

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#664]
### Context
Prior to sudo removal, we need to onboard and activate governance v1.0 (= old standard governance pallets) for Litmus.

### Task
At least the following:
- [ ] [Finalize and reset council/tech-committee members](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/666)
- [ ] [Double-check the runtime parameters and configuration](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/667)
- [ ] [Test/trialrun of motions/proposals on rococo, along with governance-apps](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/668)
- [ ] [Activate governance on Litmus (baseCallFilter, configuration, release, runtime upgrade)](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/669)
- [ ] [Test/trialrun of motions/proposals on Litmus, along with governance-apps](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/670)
- [ ] [Announcement, depending on how many LIT tokens are available on Litmus, we can experimentally carry out the next runtime upgrade using referrenda](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/671)

### Acceptance criteria
Governance v1.0 pallets are onboarded and activated.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
