### ISSUE TITLE
Initial implementation of IMT

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#689]
### Context
Kick off the initial implementation of IMT (**I**dentity **M**anagement pallet in **T**EE). It doesn't have to be perfect, but just to get the ball rolling.
For a proposal of interface/data structure please check the notion doc.

### Task
Ideally, the implementation should contain the following:
- [x] `IDGraph` struct definition
- [x] common utility like decoding/deserialization, if applicable
- [x] extrinsic impl
- [x] optional events and internal pub fn that are called by teerex (could be done later)
- [x] proper unittests

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I'm not sure about which priority tag to apply @StamfordDigital, as it's obviously with high priority but will probably take more than 5 days.
