### ISSUE TITLE
Bi-directional token bridge for Litmus

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#696]
### Context
This ticket could be an epic.
The current token bridge on Litmus is uni-directional (ETH => Litmus), we'd like to extend it to allow LIT transfer in the other direction. We could either use ChainSafe or Subbridge (from Phala) for it.

### Task
- [ ] investigate and decide which bridge solution to use (we are currently using chainSafe for ETH => Litmus)
- [ ] adjustment in code (pallet/runtime)
- [ ] ETH contract deployment and/or adjustment
- [ ] devops and configuration setup for the bridges
- [ ] Communicate with F/E team to test the bi-directional bridge

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Update after a short sync: we still prefer ChainSafe for now

**Comment by Kailai-Wang** [comment]
@zhizming-zhong you could write your current status here if you still need some time
