### ISSUE TITLE
Accept and test XCM with moonriver

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#717]
### Context
Moonriver's [referendum](https://moonriver.subscan.io/referenda/104) of accepting our channel opening request is being passed. We need to accept their request too and try to transfer LIT as xcLIT

### Task
- [x] accept their request
- [x] transfer LIT to moonriver as xcLIT
- [x] transfer LIT back to litmus, if applicable

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
The channel opening request from moonriver is accepted.

**Comment by Kailai-Wang** [comment]
Tested transfering LIT to moonriver using F/E UI: the transfer was successful; the extrinsic is marked as "success" too [on subscan](https://litmus.subscan.io/extrinsic/0xa36b700f8ce8ad77911395e58213e880c55bdcc2add53663930228c9064731f2).

I didn't find a way to see xcLIT from moonriver app => no xcLIT listed on their https://apps.moonbeam.network/moonriver. I believe this is something that they have to work with.

However, on the asset panel I do see 1 XCLIT available, which probably signals the success of transfer too:
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/7630809/180309354-a86b87b9-6976-41c4-a92b-892ce3c315e8.png">

**Comment by Kailai-Wang** [comment]
Another question is who is paying the fee, is it our litentry sovereign account on KSM? I assume KSM needs to be used to pay XCM fees?
