### ISSUE TITLE
Consider using orml_xcm to accelerate UMP XCM

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#725]
### Context
orml_xcm provides a wrapper to call `pallet_xcm::send_xcm` with `Here` origin, which is an easier to achieve native origin in comparison with sudo call. pallet_xcm can achieve similar power control with proper implementation of sending origin

### Task
- [x] comparing orml_xcm pallet and pallet_xcm, implemented new sending origin for pallet_xcm
- [x] set origin and callFilter
- [x] ideally with integration test

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
This needs to be brought on to the table soon, as we plan to remove sudo in the near future.

@wangminqi can you do that? Alternatively I can do it too

**Comment by wangminqi** [comment]
On it.

**Comment by wangminqi** [comment]
I do not feel it is a necessary pallet. We have many alternative choices under the current XCM implementation. current pallet_xcm can do exactly the same (sovereign account of parachain at remote side)

**Comment by wangminqi** [comment]
Discussed. The Context of issue updated.
