### ISSUE TITLE
Introduce taplo for TOML formatting

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#728]
### Context
It's always beneficial to have a standard format. I tried taplo myself as TOML formatter and it looked good. I suggest integrating it as a standard TOML formatter for our repo.
https://github.com/tamasfe/taplo
https://taplo.tamasfe.dev/cli/introduction.html

### Task
- [x] encourage people to use it to format TOML files before submitting code
- [x] integrate taplo into CI
- [x] optionally adjust pre-commit hooks

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
