### ISSUE TITLE
Activation of staking pallet on Litentry -- collators rollout

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#760]
### Context
As we are about to finalize the implementation of the staking functionality on Litentry, we'd like to devise a rollout plan for it. Basically, it should contain several stages and we shouldn't advance to the next stage until we are sure everything works fine in the current stage. The stages are:
1. migrate the collator selection mechanism and current collators (- collator_selection pallet, + staking pallet)
2. open 1-2 extra collator slot and observe the block production
3. adjust tokenomics if needed
4. enable delegation with stake
5. extend the collator set size

### Task
The following need to be done for a production env:
- [x] Staking rollout phase 1 - reconfirming the pallet-staking parameters for Litentry runtime
- [x] Staking rollout phase 1 - runtime upgrade on Litentry including the migration to switch to staking pallet for collator selection
- [x] #797
- [x] #798
- [x] #799
- [x] #800

Frontend:
- [x] Frontend integration for parachain staking => requirements TBD

It's a high-priority task (epic) but we still have to go steadily

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
@Kailai-Wang Are these documents for developers or the community?

**Comment by Kailai-Wang** [comment]
> @Kailai-Wang Are these documents for developers or the community?

Depends on the way we want the community to interact with the staking module.
Ideally we'll have a nice made frontend UI but that takes time.

If participating in collation is not too complex with polkadot-js, we can simply publish a how-to guide.

**Comment by wangminqi** [comment]
done.
