### ISSUE TITLE
Move `MaximumIssuance` to storage type

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#761]
### Context
We'd like to change `MaximumIssuance` from constant to storage type to allow immediate control from privileged origin.

### Task
- [x] change `MaximumIssuance` to StorageValue, with a default value
- [x] a setter for it
- [x] a dedicated origin to set `MaximumIssuance`
- [x] runtime upgrade on rococo and test

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
@wangminqi Does it affect the logic of calculating `ExternalBalances`? If so we should update it within the setter

**Comment by Kailai-Wang** [comment]
All tasks are done, this ticket can be closed.
