### ISSUE TITLE
Sudo removal on Litmus

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#775]
### Context
We are aiming to remove sudo on Litmus in two weeks (basically give the bi-directional token bridge some time and observe how well it works)

### Task
- [x] double-check origin control
- [x] remove sudo pallet and code adjustment
- [x] do we need any migrations? A: Yes, remove sudo storage
- [x] balance transfer activation

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
balance transfer activated, sudo removal should be followed soon

**Comment by Kailai-Wang** [comment]
Hi @wangminqi I reassign this ticket to you -- we are looking forward to removing sudo by end of next week at the latest.
