### ISSUE TITLE
Rework on the (user's) shielding key

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#828]
### Problem

We use the user's shielding(public) key to encrypt the user-sensitive data when passing it back. Currently we have chosen RSA (2048 bit or 3072 bit) as it's the opposite side of TEE's shielding key which is a 3072 bit RSA key. However, RSA is only able to encrypt data [to a maximum amount equal to the key size](https://security.stackexchange.com/questions/33434/rsa-maximum-bytes-to-encrypt-comparison-to-aes-in-terms-of-security), minus any padding and header data (which depends on the padding scheme). So it means if we have 3072-bit RSA, we can only encrypt up to `3072 / 8 - 11 = 373` bytes of data for `PKCS1_V1.5` padding scheme. This restriction has an effect on both:
1. the encoded length of `TrustedCall` which will be encrypted by TEE's shielding key, and
2. the length of returned data which will be encrypted by the user's shielding key (e.g. VC)

For 1 it's problematic, among other things, to handle `TrustedCall::set_user_shielding_key(AccountId, AccountId, UserShieldingKey)`: based on the [code](https://github.com/litentry/tee-worker/blob/1a2f53db5ac88dd069a368e0aa7694bc49e34158/app-libs/stf/src/lib.rs#L288-L291) the `TrustedCall` struct contains the encoded call itself as well as a signature, which at least doubles the size. So if we use 2048-bit RSA as the user's shielding key, the `UserShieldingKey` would be 256 bytes (a rough calculation, just ignore all the encoding of bytes and n/e) and the resulting encoded `TrustedCall` would be easily more than 256 * 2 = 512 bytes, in fact, in our test we get almost 1000 bytes for the final encoded call. This doesn't fit into TEE's shielding key: if you try to encrypt it with TEE's shielding key, you would get the error `text too long`.

For 2 we are unsure of the size of a typical VC yet, but it definitely **could** be more than 256 bytes and we have to face the same problem again.

### Potential solutions

There're multiple ways to solve this (I take problem 1 for example, the solution will be similar for problem 2)

1. We rely on external storage(e.g. IPFS) to store the (encrypted) shielding key and only pass the link around. Within the enclave we retrieve the IPFS content, decrypt it to get the user's shielding key and store it in the sidechain
2. We split the key into several chunks and re-assemble them in the enclave when we get all parts. In this case the F/E will have to do a batch call of the following exemplary extrinsics:
    ```
    set_user_shielding_key_part1()
    set_user_shielding_key_part2()
    set_user_shielding_key_part3()
    set_user_shielding_key_part4()
    ```
3. We drop the RSA key pair and go for **symmetric** encryption. In this case the user's shielding key is something like AES-GCM shared key. The workflow is the same: the user/IDHLS generates a random AES key and encrypt it with TEE's shielding key and sends it over to TEE via parachain extrinsics. It's basically a simplified version of [HTTPS handshakes](https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/).

Personally, I (surely) prefer **option 3**. It gives us the following benefits:
- no limit of the encrypted text length
- faster than RSA encryption
- the key length itself is significantly shorter (16 bytes or 32 bytes, so the encoded TrustedCall will fit into TEE's encryption)

And all these are achieved without compromising the security:
- from the client side (user), TEE shielding key is public and retrievable from parachain, so the user knows he/she is talking to the right server(TEE)
- from the server side (TEE), we know it comes from the right user as blockchain guarantee's the extrinsic calling logic (it has to be signed by the user) and we verify that the extrinsic caller's account is the same as the account whose shielding key is going to be updated. So you can only set shielding key for yourself (= the extrinsic's origin).

However, to achieve that, we need to:
- make sure the `set_user_shielding_key()` extrinsic is called by the user/IHDLS, not IHDCS.  cc @kaylawangnow
- discard the `teerex::call_worker` and write our own function and handlers inside tee-worker, a bit more coding.

### What about the usecase "User A wants to authorize/delegate user B to set A's shielding key`?
It's possible, but probably we'll do it in later versions. To make it happen, we need to attach a signature from user A as extrinsic parameters, we'd like to make sure all the verification logic happens **on-chain or inside TEE.**

### Tasks
- [x] https://github.com/litentry/litentry-parachain/issues/829
- [x] https://github.com/litentry/litentry-parachain/issues/830
- [x] https://github.com/litentry/tee-worker/issues/57
- [x] https://github.com/litentry/tee-worker/issues/58

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
While Option3 introduces additional refactoring on re-writing our own functions and handlers inside tee-worker, it has the most in terms of scalability(Option2) and performance(Option1). 

Totally agree with you.

**Comment by kaylawangnow** [comment]
sounds good will change FE workflow according to option3

**Comment by jonalvarezz** [comment]
Sounds good to me too.

Regardless of the type of encryption it must be stored and managed by the user/IHDLS

**Comment by Kailai-Wang** [comment]
All tasks solved. Close this ticket now
